server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:~/ms-cards;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
